// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdvCIR5WkmQl2yU3q7avRQ4oqP8k65ws',
    appId: '1:266695692193:web:7c0808dcb288115d98c5e0',
    messagingSenderId: '266695692193',
    projectId: 'meal-match-93f06',
    authDomain: 'meal-match-93f06.firebaseapp.com',
    storageBucket: 'meal-match-93f06.appspot.com',
    measurementId: 'G-1TW7XZP93V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBna8FRvuoNaXMrd8IT_K8kfM8morUuj5I',
    appId: '1:266695692193:android:a41b2216c66cf0e098c5e0',
    messagingSenderId: '266695692193',
    projectId: 'meal-match-93f06',
    storageBucket: 'meal-match-93f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaTpr73eH7JEOzG-Jil8GdcWFC3qSaH0M',
    appId: '1:266695692193:ios:b2f8c0792d398fff98c5e0',
    messagingSenderId: '266695692193',
    projectId: 'meal-match-93f06',
    storageBucket: 'meal-match-93f06.appspot.com',
    iosBundleId: 'com.example.cookUp',
  );
}
